//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M7_TrabalhoModelo_t1.Admin.Disciplinas
{


    public partial class Adicionar
    {
    }
}
